version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: production.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: dew77/studentguide2-backend
    env_file: production.env
    depends_on:
      - db
    volumes:
      - static:/app/static/
  gateway:
    image: dew77/studentguide2-gateway
    volumes:
      - static:/usr/share/nginx/html/static/
    ports:
      - 80:80
      - 443:443