# Generated by Django 4.2.5 on 2023-09-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_proforg',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_starosta',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
    ]
